name: Gradle Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK 16
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.7
        with:
          arguments: |
            clean
            build
            shadowJar
      - name: Move the artifact
        run: |
          mkdir staging
          mv api/build staging/api
          mv bundle/build staging/bundle
          mv core/build staging/core
          mkdir staging/features
          mv features/autostore/build staging/features/autostore
          mv features/category/build staging/features/category
          mv features/command/build staging/features/command
          mv features/craft/build staging/features/craft
          mv features/gui/build staging/features/gui
          mv features/notifier/build staging/features/notifier
          mv features/stick/build staging/features/stick
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Package
          path: staging
